# Linear algebra

In [2]:
import numpy as np

In [3]:
np.__version__

'1.14.2'

## Matrix and vector products

Q1. Predict the results of the following code.

In [4]:
x = [1,2]
y = [[4, 1], [2, 2]]
#print np.dot(x, y)
#print np.dot(y, x)
#print np.matmul(x, y)
#print np.inner(x, y)
#print np.inner(y, x)

In [13]:
print(np.dot(x, y))
print(np.dot(y, x))
print(np.matmul(x, y))
print(np.inner(x, y))
print(np.inner(y, x))
print(np.matmul(y, x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [52]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
#print np.dot(y, x)
#print np.matmul(y, x)


In [4]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))

[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [37]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
#print np.vdot(x, y)
#print np.vdot(y, x)
#print np.dot(x.flatten(), y.flatten())
#print np.inner(x.flatten(), y.flatten())
#print (x*y).sum()

In [7]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


Q4. Predict the results of the following code.

In [45]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
#print np.inner(x, y)
#print np.inner(y, x)
#print np.outer(x, y)
#print np.outer(y, x)

In [8]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print(np.outer(x, y))
print(np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [97]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)


[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [10]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
np.linalg.cholesky(x)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

Q6. Compute the qr factorization of x and verify it.

In [107]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)


q=
[[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [16]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q,r = np.linalg.qr(x)
print('q=',q,'\nr=',r)

q= [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r= [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [165]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)


U=
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
[ 3.          2.23606801  2.          0.        ] 
V=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [17]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
np.linalg.svd(x)

(array([[ 0.,  1.,  0.,  0.],
        [ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.],
        [ 0.,  0.,  1.,  0.]], dtype=float32),
 array([3.      , 2.236068, 2.      , 0.      ], dtype=float32),
 array([[-0.       ,  0.       ,  1.       , -0.       ,  0.       ],
        [ 0.4472136, -0.       , -0.       , -0.       ,  0.8944272],
        [-0.       ,  1.       ,  0.       , -0.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       ,  1.       ,  0.       ],
        [-0.8944272,  0.       ,  0.       ,  0.       ,  0.4472136]],
       dtype=float32))

## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [77]:
x = np.diag((1, 2, 3))


eigenvalues are
[ 1.  2.  3.]
eigenvectors are
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [24]:
x = np.diag((1, 2, 3))
print(np.linalg.eigvals(x))
print(np.linalg.eig(x)[1])

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
eigenvals = np.linalg.eigvals(x)
eigenvecs = np.linalg.eig(x)[1]

Q9. Predict the results of the following code.

In [81]:
#print np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)

In [27]:
print(np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [12]:
x = np.arange(1, 10).reshape((3, 3))


16.8819430161
4.56177073661e+17


In [37]:
x = np.arange(1, 10).reshape((3, 3))
print(np.linalg.norm(x,ord="fro"))
print(np.linalg.cond(x,p="fro"))

16.881943016134134
4.561770736605098e+17


Q11. Calculate the determinant of x.

In [22]:
x = np.arange(1, 5).reshape((2, 2))


-2.0


In [38]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)

-2.0000000000000004

Q12. Calculate the rank of x.

In [35]:
x = np.eye(4)


4


In [44]:
x = np.eye(4)
np.linalg.svd(x)[1].size

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [49]:
x = np.arange(1, 5).reshape((2, 2))



-1.0 0.69314718056


In [47]:
x = np.arange(1, 5).reshape((2, 2))
sign, logdet = np.linalg.slogdet(x)
print(sign,' ',logdet)

-1.0   0.6931471805599455


In [50]:
np.log(-np.linalg.det(x))

0.6931471805599455

Q14. Return the sum along the diagonal of x.

In [57]:
x = np.eye(4)


4.0


In [52]:
x = np.eye(4)
sum(np.diag(x))

4.0

In [53]:
np.trace(x)

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [60]:
x = np.array([[1., 2.], [3., 4.]])



[[-2.   1. ]
 [ 1.5 -0.5]]


In [54]:
x = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(x)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])